- .bazelignore
- .gitignore
- BUILD
- WORKSPACE
- patches/0002-opentelemetry-tracer-lib-visibility.patch
- source/extensions/http/early_header_mutation/trace_context/BUILD
- source/extensions/http/early_header_mutation/trace_context/trace_context.cc
- source/extensions/http/early_header_mutation/trace_context/trace_context.h
- source/extensions/http/early_header_mutation/trace_context/trace_context_test.cc
- source/extensions/tracers/pomerium_otel/BUILD
- source/extensions/tracers/pomerium_otel/config.cc
- source/extensions/tracers/pomerium_otel/config.h
- source/extensions/tracers/pomerium_otel/pomerium_otel.proto
- source/extensions/tracers/pomerium_otel/pomerium_otel_test.cc
- source/extensions/tracers/pomerium_otel/span.cc
- source/extensions/tracers/pomerium_otel/span.h
- source/extensions/tracers/pomerium_otel/tracer_impl.cc
- source/extensions/tracers/pomerium_otel/tracer_impl.h
- source/extensions/tracers/pomerium_otel/typeutils.h
This adds a new tracer extension called pomerium_otel, which extends the default opentelemetry tracer and adds a couple of additional pomerium-specific features:
When starting a span:
- If the associated HTTP request contains an `x-pomerium-traceparent` or `x-pomerium-traceid` header (set in the early header mutation extension), the randomly generated trace ID will be replaced with the trace ID contained in the header value.
- If the associated HTTP request contains the `x-pomerium-sampling-decision` header, the sampling decision will be forced on or off, depending on the value of the header ("1" or "0" respectively).
If configured, Envoy will use a route's decorator as the span operation name for spans created from HTTP requests for that route. This extends the otel Span to override its …
> add pomerium_otel tracer extension

- BUILD
It looks like this feature is not compatible with Xcode 16.3: linking fails with the error `ld: library 'crt0.o' not found`.
> do not set fully_static_link on macOS

- source/common/status.h
I think this builds on clang 19 but not on clang 18. Either way it doesn't need to be constexpr.
> remove constexpr from statusf

- .bazelrc
- .github/workflows/test-linux.yaml
- .gitignore
- api/extensions/filters/network/ssh/BUILD
- tools/run_envoy_bazel_coverage.sh
Add a CI check to run `bazel test //...` on Linux.
This is loosely based on https://github.com/pomerium/envoy-build/blob/main/.github/workflows/build-linux.yaml.
> ci: add a workflow to run tests on linux

- source/common/math.h
- test/common/BUILD
- test/common/math_test.cc
The internal function std::__sub_sat isn't available in clang 18. The implementation is trivial, so we can just write it ourselves.
> common/math: replace sub_sat implementation

- .github/workflows/test-linux.yaml
- tools/run_envoy_bazel_coverage.sh
- tools/setup_clang.sh
Switching to clang-19 for CI builds for better C++23 support, including:
- constexpr std::variant
- Full support for [P2448R2](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2022/p2448r2.html)
- Full support for [deducing this](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2021/p0847r7.html)
- std::out_ptr
Envoy has a setup script that I vendored in which can configure a non-default clang toolchain.
> ci: use clang-19 with envoy setup script

- .github/workflows/test-linux.yaml
Coveralls needs specific config to handle matrix builds, to let each build upload coverage.
https://docs.coveralls.io/parallel-builds
> ci: add parallel build config to coveralls upload

- .github/workflows/test-linux.yaml
I thought that github would just reuse the runner if the runs-on constraint was the same, but that turns out not to be the case.
> ci: fix upload-coverage job to run on ubuntu-latest

- source/extensions/filters/network/ssh/wire/messages.h
- test/extensions/filters/network/ssh/wire/messages_bench_test.cc
- test/extensions/filters/network/ssh/wire/messages_test.cc
This makes a small adjustment how concrete messages are converted to wire::Message, requiring the caller to explicitly specify whether they want to copy or move the message in cases where it could be ambiguous.
> wire: add conditional explicit specifier to Message constructor

- source/extensions/filters/network/ssh/BUILD
- source/extensions/filters/network/ssh/packet_cipher.cc
- source/extensions/filters/network/ssh/packet_cipher.h
- test/extensions/filters/network/ssh/BUILD
- test/extensions/filters/network/ssh/packet_cipher_test.cc
- test/extensions/filters/network/ssh/test_mocks.cc
- test/extensions/filters/network/ssh/test_mocks.h
This adds the DirectionalPacketCipher abstractions, PacketCipher type (a concrete container for two DirectionalPacketCiphers, one of each direction), and the 'NoCipher' unencrypted directional cipher implementation.
> ssh network filter (3/24): add packet cipher abstractions and common logic

- source/extensions/filters/network/ssh/BUILD
- source/extensions/filters/network/ssh/kex_alg.cc
- source/extensions/filters/network/ssh/kex_alg.h
- source/extensions/filters/network/ssh/wire/packet.h
- test/extensions/filters/network/ssh/BUILD
- test/extensions/filters/network/ssh/kex_alg_test.cc
This adds the base KexAlgorithm type, common key exchange-related structs, and shared logic to compute exchange hashes and generate/verify exchange hash signatures.
> ssh network filter (4/24): add kex algorithm abstractions and common logic

- source/extensions/filters/network/ssh/kex_alg.h
- test/extensions/filters/network/ssh/kex_alg_test.cc
It doesn't make much sense to look up the hash alg from inside KexAlgorithm, since implementations (e.g. curve25519-sha256) have the hash algorithm as an intrinsic property of the kex algorithm. Also makes it hard to mock out algorithms that don't exist in openssh.
> ssh: make hash algorithm part of KexAlgorithm implementation instead of using openssh lookup

- test/extensions/filters/network/ssh/BUILD
- test/extensions/filters/network/ssh/kex_alg_curve25519_test.cc
- test/extensions/filters/network/ssh/kex_alg_test.cc
- test/extensions/filters/network/ssh/openssh_test.cc
- test/extensions/filters/network/ssh/packet_cipher_etm_test.cc
- test/extensions/filters/network/ssh/service_userauth_test.cc
- test/test_common/BUILD
- test/test_common/test_common.h
Extract the duplicated `randomBytes()` function to test_common.h.
Fix some formatting issues.
> add randomBytes() to test_common.h

- source/extensions/filters/network/ssh/wire/encoding.h
- test/extensions/filters/network/ssh/wire/encoding_test.cc
Decoding an empty list with the LengthPrefixed option was an error, but it should not be. 
There is one message with a field that is encoded like this (HostKeysProveRequestMsg), and while it doesn't make much sense to ask the server to prove 0 keys, the empty message was not being decoded correctly and erroring in the wrong place.
> wire: decoding empty length-prefixed lists should not error

- source/extensions/filters/network/ssh/service_connection.cc
- source/extensions/filters/network/ssh/service_connection.h
- test/extensions/filters/network/ssh/BUILD
- test/extensions/filters/network/ssh/service_connection_test.cc
- test/extensions/filters/network/ssh/test_mocks.cc
- test/extensions/filters/network/ssh/test_mocks.h
Add unit tests for the connection service.
Related issue: https://linear.app/pomerium/issue/ENG-2451/ssh-protocol-21-service-connection
> ssh network filter (21/24): connection service unit tests

- BUILD
- WORKSPACE
- patches/envoy/tmp-fix-upstream-connection-callbacks.patch
- Updates the //:envoy target to build the ssh extension
- Adds the missing //:refresh_compile_commands target
- Adds the upstream connection callbacks fix patch (still need to submit this upstream)
> ssh: build config updates

- source/extensions/filters/network/ssh/service_userauth.cc
- source/extensions/filters/network/ssh/service_userauth.h
- test/extensions/filters/network/ssh/service_userauth_test.cc
- Adds a limit of 6 auth failure attempts before disconnecting
- Ensures the "none" auth request can only be sent once.
> ssh: add limit on auth failures and 'none' auth requests

- source/extensions/filters/network/ssh/version_exchange.cc
- test/extensions/filters/network/ssh/server_transport_test.cc
- test/extensions/filters/network/ssh/version_exchange_test.cc
This was refactored at some point to _include_ the trailing \r\n in the final version exchange strings passed to the callback. IIRC the thinking was that if the client only sent \n and not \r\n (since we are lenient about it), this difference would need to be kept track of, but I don't think that is actually the case. The logic to compute the exchange hash wasn't updated though, leading to the session identifier being incorrect, but it's less confusing if we just remove the suffix right away.
> version exchange: remove crlf suffix from version before passing to callback

- source/extensions/filters/network/ssh/openssh.cc
- source/extensions/filters/network/ssh/openssh.h
- source/extensions/filters/network/ssh/service_userauth.cc
- source/extensions/filters/network/ssh/service_userauth.h
- source/extensions/filters/network/ssh/wire/messages.h
- test/extensions/filters/network/ssh/openssh_test.cc
- test/extensions/filters/network/ssh/service_userauth_test.cc
- test/extensions/filters/network/ssh/wire/messages_test.cc
When making a userauth request to an upstream server, check for the server-sig-algs extension, and generate one of the server's preferred keys (if supported).
> ssh: upstream server-sig-algs support

- api/extensions/filters/network/ssh/ssh.pb.go
- api/extensions/filters/network/ssh/ssh.proto
- source/extensions/filters/network/ssh/openssh.cc
- source/extensions/filters/network/ssh/openssh.h
- source/extensions/filters/network/ssh/service_userauth.cc
- test/extensions/filters/network/ssh/openssh_test.cc
- test/extensions/filters/network/ssh/server_transport_test.cc
- test/extensions/filters/network/ssh/service_userauth_test.cc
Adds a field public_key_fingerprint with the pre-computed raw fingerprint of the public key to PublicKeyMethodRequest, so that pomerium doesn't need to compute it itself. It is passed as raw bytes, so pomerium can format it as needed to use as the session identifier.
> ssh: add pre-computed fingerprint to user auth request

- source/extensions/filters/network/ssh/service_userauth.cc
- source/extensions/filters/network/ssh/service_userauth.h
- test/extensions/filters/network/ssh/service_userauth_test.cc
This adds a few extra checks during public key auth:
- the public key algorithm name must match the given key (an incorrect algorithm name would have still failed, but only after a signature was given, during verification. This check will cause it to fail earlier with a more obvious error message)
- the same key cannot be attempted more than once
- a maximum of 10 public keys can be attempted
> ssh: additional validation and limits for public key auth requests

- api/extensions/filters/network/ssh/ssh.pb.go
- api/extensions/filters/network/ssh/ssh.pb.validate.go
- api/extensions/filters/network/ssh/ssh.proto
- source/extensions/filters/network/ssh/openssh.cc
- source/extensions/filters/network/ssh/openssh.h
- source/extensions/filters/network/ssh/service_userauth.cc
- test/extensions/filters/network/ssh/client_transport_test.cc
- test/extensions/filters/network/ssh/openssh_test.cc
- test/extensions/filters/network/ssh/service_userauth_test.cc
This configures the permissions and start/end timestamps of user certs based on the values provided in the publickey auth response from pomerium. 
Also, renamed valid_after/valid_before -> valid_start_time/valid_end_time, the former is too error-prone.
> ssh: configure user certs from pomerium auth response

- source/extensions/filters/network/ssh/service_userauth.cc
- source/extensions/filters/network/ssh/service_userauth.h
- test/extensions/filters/network/ssh/service_userauth_test.cc
This fixes https://github.com/pomerium/envoy-custom/pull/77, which didn't account for signature-less attempts (oops)
> ssh: fix logic for duplicate public key attempts

- source/extensions/filters/network/ssh/service_userauth.cc
- source/extensions/filters/network/ssh/service_userauth.h
- test/extensions/filters/network/ssh/service_userauth_test.cc
The duplicate key check is complicated and has many edge cases. It ostensibly doesn't matter much for our auth flow anyway, so replacing with a fixed maximum attempt limit of 40.
> ssh: replace duplicate public key check with a fixed limit on auth requests

- source/extensions/filters/network/ssh/grpc_client_impl.cc
- source/extensions/filters/network/ssh/grpc_client_impl.h
- source/extensions/filters/network/ssh/server_transport.cc
- test/extensions/filters/network/ssh/grpc_client_impl_test.cc
- test/extensions/filters/network/ssh/server_transport_test.cc
Reverts pomerium/envoy-custom#85
The downstream connection is not available in setCodecCallbacks as initially thought. This will take some more time to figure out.
> Revert "ssh: populate source_address in DownstreamConnectEvent"

- WORKSPACE
- patches/envoy/0005-suppress-duplicate-wip-warnings.patch
This adds the same duplicate-suppression logic to wip warnings that exists for other validation warnings. These are especially noisy and only need to be logged once. Without the duplicate check, they are logged again on every config change.
> envoy: suppress duplicate wip validation warnings

- source/extensions/filters/network/ssh/client_transport.cc
- source/extensions/filters/network/ssh/client_transport.h
- source/extensions/filters/network/ssh/config.cc
- source/extensions/filters/network/ssh/config.h
- source/extensions/filters/network/ssh/kex.cc
- source/extensions/filters/network/ssh/kex.h
- source/extensions/filters/network/ssh/openssh.cc
- source/extensions/filters/network/ssh/openssh.h
- source/extensions/filters/network/ssh/server_transport.cc
- source/extensions/filters/network/ssh/server_transport.h
- source/extensions/filters/network/ssh/service_userauth.cc
- source/extensions/filters/network/ssh/service_userauth.h
- source/extensions/filters/network/ssh/transport.h
- source/extensions/filters/network/ssh/transport_base.h
- test/extensions/filters/network/ssh/client_transport_test.cc
- test/extensions/filters/network/ssh/config_test.cc
- test/extensions/filters/network/ssh/kex_test.cc
- test/extensions/filters/network/ssh/openssh_test.cc
- test/extensions/filters/network/ssh/server_transport_test.cc
- test/extensions/filters/network/ssh/service_connection_test.cc
- test/extensions/filters/network/ssh/service_userauth_test.cc
- test/extensions/filters/network/ssh/test_mocks.h
- test/extensions/filters/network/ssh/transport_base_test.cc
This moves initialization of the ssh host keys and user ca key into `SshCodecFactoryConfig::createCodecFactory`. If an exception is thrown here, it will be caught by XDS which will reject the invalid listener config. The keys are now accessed using a `SecretsProvider` abstraction which is implemented by the `SshCodecFactory`, so that other components of the system do not need to load the keys themselves and handle errors.
Fixes https://github.com/pomerium/envoy-custom/issues/98
> ssh: improve handling of key loading errors

- source/extensions/filters/network/ssh/wire/encoding.h
- test/extensions/filters/network/ssh/wire/encoding_bench_test.cc
Small change to remove the temporary Buffer::OwnedImpl from a couple of encoding functions. The buffers actually have quite a large inline capacity; sizeof(Buffer::OwnedImpl) is 1120 bytes, so they aren't very light-weight.
> ssh/wire: remove temporary buffers in some encoding routines

- test/extensions/filters/network/ssh/transport_base_test.cc
https://github.com/pomerium/envoy-custom/actions/runs/17748373944/job/50438371900
Doesn't look like there is a bug here, this test sometimes just takes more than 10 seconds to run.
> ssh: increase default thread timeout in transport_base_test

- source/extensions/filters/network/ssh/channel.h
- source/extensions/filters/network/ssh/client_transport.cc
- source/extensions/filters/network/ssh/service_connection.cc
- source/extensions/filters/network/ssh/service_connection.h
- test/extensions/filters/network/ssh/client_transport_test.cc
- test/extensions/filters/network/ssh/service_connection_test.cc
- Removes the status return from sendMessageLocal
- Also set the recipient channel ID automatically for sendMessageRemote (we do this already for sendMessageLocal)
> ssh: improve status handling in ChannelCallbacks api

- source/extensions/filters/network/ssh/client_transport.cc
- source/extensions/filters/network/ssh/wire/messages.cc
- source/extensions/filters/network/ssh/wire/messages.h
- test/extensions/filters/network/ssh/client_transport_test.cc
- test/extensions/filters/network/ssh/server_transport_test.cc
- test/extensions/filters/network/ssh/service_connection_test.cc
- test/extensions/filters/network/ssh/test_mocks.h
- test/extensions/filters/network/ssh/wire/test_field_reflect.h
- test/test_common/test_common.h
Adds new sub-message types for ChannelOpenMsg: 
- `SessionChannelOpenMsg` 
- `X11ChannelOpenMsg` 
- `ForwardedTcpipChannelOpenMsg` 
- `DirectTcpipChannelOpenMsg`
Instead of hard-coding channel type strings, these request types can be used instead. For channel types that have extra data attached to them, the strongly-typed messages are less error-prone.
> ssh: add ChannelOpen sub-messages for known channel types

- source/extensions/filters/network/ssh/client_transport.cc
- test/extensions/filters/network/ssh/client_transport_test.cc
This would have been caught by integration tests, which are only in the pomerium repo (maybe we should have some here as well?)
> ssh: fix handoff middleware binding downstream ID twice

- WORKSPACE
- patches/envoy/tmp-transport-socket-options.patch
- source/extensions/filters/network/ssh/BUILD
- source/extensions/filters/network/ssh/client_transport.cc
- source/extensions/filters/network/ssh/filter_state_objects.cc
- source/extensions/filters/network/ssh/filter_state_objects.h
- source/extensions/filters/network/ssh/frame.h
- source/extensions/filters/network/ssh/server_transport.cc
- test/extensions/filters/network/ssh/BUILD
- test/extensions/filters/network/ssh/client_transport_test.cc
- test/extensions/filters/network/ssh/filter_state_objects_test.cc
- test/extensions/filters/network/ssh/frame_test.cc
- test/extensions/filters/network/ssh/server_transport_test.cc
Working on implementing filter state object sharing in upstream generic_proxy, which is currently missing. This removes the need for us to manually pass the objects through the request header message and extract them in the client codec.
This is needed because we have to propagate the `downstream_source_address` and `requested_server_name` filter state objects through to the upstream transport socket to enable reverse tunneling ssh routes.
> ssh: temp patch - implement filter state object sharing in generic_proxy
